name: "workflow commands"

on:
    push:
        branches:
            main
jobs:
    my-job:
        runs-on: ubuntu-latest
        steps:
            - name: "groups logging"
              run: |
                echo "::group::My Group Message"
                echo "Msg 1"
                echo "Msg 2"
                echo "::endgroup::" 

